### ISSUE TITLE
Rotate camera orientation

### ISSUE THREAD

**Issue by hoangdado** [zweigraf/face-landmarking-ios#5]
I had tried to set the camera orientation to Landscape or Portrait but the below code (in DlibWrapper.mm) still return width = 640 and height = 480 (with preset is AVCaptureSessionPreset640x480).
`size_t width = CVPixelBufferGetWidth(imageBuffer);`
`size_t height = CVPixelBufferGetHeight(imageBuffer);`
Then I couldn't  do the landmark detection in Portrait view. Could you fix it?

**Comment by stanchiang** [comment]
^bump

same issue, more or less. i updated my plist to show portrait w/ home button at bottom (normal orientation) and attached the result. the "face landmark mask" is drawn upright but, the camera feed is rotated landscape. 

@zweigraf maybe you could find some time to document how you construct your image? I've rotated AVCaptureVideoPreviewLayer before but rotating AVSampleBufferDisplayLayer doesn't seem possible since i couldn't find examples off google.

![img_3615](https://cloud.githubusercontent.com/assets/3621407/17459849/18602960-5c00-11e6-8410-08ba518f6c25.PNG)

**Comment by hoangdado** [comment]
@stanchiang I found that if you change the camera orientation to portrait or landscape the values still are width = 640 and height = 480. I think it maybe the camera hardware will alsway output the buffer with this size. What you can do is rotating the image when copying pixel value from CVPixelBuffer to dlib::array2d<dlib::bgr_pixel>. In addition you need to rotate the input face rect. 
I fixed the issue by doing that, but I got the performance problem. The doWorkOnSampleBuffer method consume too much CPU.

**Comment by stanchiang** [comment]
can you add some sample code for your implementation? i was trying to do something like that but it wasn't working right.

**Comment by hoangdado** [comment]
For copying pixel values:
   ```
    img.reset();
    long position = 0;
    
    while (img.move_next()) {
        lib::bgr_pixel& pixel = img.element();
        
        size_t row = position / height;
        size_t col = position % height;
        
        long bufferLocation = (col * width + row) * 4;

        char b = baseBuffer[bufferLocation];
        char g = baseBuffer[bufferLocation + 1];
        char r = baseBuffer[bufferLocation + 2];
        
        dlib:: bgr_pixel newpixel(b, g, r);
        pixel = newpixel;
        
        position++;
    }
```
For rotate face rect, I think you should code yourself for convenience. You only need to change the `oneFaceRect`.

**Comment by ArtSebus** [comment]
@hoangdado this code doesn't work for me, have you tested this ?

**Comment by teresakozera** [comment]
Well, I also faced this problem. I didn't solve it but moved a little bit. Firstly, in the Target -> General:
![screen shot 2016-08-08 at 16 27 43](https://cloud.githubusercontent.com/assets/10118916/17485287/224ed7e2-5d85-11e6-88c2-e13849ff220e.png)

Next thing- 'SessionHandler.swift':

`func captureOutput(captureOutput: AVCaptureOutput!, didOutputSampleBuffer sampleBuffer: CMSampleBuffer!, fromConnection connection: AVCaptureConnection!) {
        
        connection.videoOrientation = AVCaptureVideoOrientation.Portrait
`

And the outcome is:
![img_0130](https://cloud.githubusercontent.com/assets/10118916/17485605/0127d8ec-5d86-11e6-8fe1-119b3d2247d4.jpg)

As you can see the landmarks are very distorted.

I hope someone will find it helpful and share the solution. :)

**Comment by hoangdado** [comment]
@teresakozera I solved your problem. You only need to update `convertScaleCGRect` method as bellow:
   
   ```
    long right = (1.0 - rect.origin.y ) * size.width;
    long left = right - rect.size.height * size.width;
    long top = rect.origin.x * size.height;
    long bottom = top + rect.size.width * size.height;
```
@stanchiang You can follow this solution. It is much easier than that I recommend you before. View my fork project for source code [https://github.com/hoangdado/face-landmarking-ios](url)

**Notice:** With my fix, I don't know why the mouth landmarks is not exactly correct while the others  is perfect!

**Comment by ArtSebus** [comment]
@hoangdado  That fixed the issue, Thank you!  
My issue is  the landmarks are not so accurate for the mouth and around the face. were you able to fix it ?

**Comment by stanchiang** [comment]
@hoangdado thanks that helped a lot! 

I also had to do an affine transformation on the layer so that the output isn't mirrored the opposite way with:

        layer.setAffineTransform(CGAffineTransformMakeRotation(CGFloat(M_PI)))
        layer.setAffineTransform(CGAffineTransformScale(layer.affineTransform(), 1, -1))

**Comment by teresakozera** [comment]
@hoangdado, thank you! it works perfect, no distortion- even in the mouth region. :)

**Comment by stanchiang** [comment]
@teresakozera for me the distorting is more of a stability issue when trying to maintain the tracking as the tolerance for difference angled faces seems to have gone down a bit for me when I try moving my face and the mask gets jittery. 

Am I facing a different issue than you guys?

**Comment by teresakozera** [comment]
@stanchiang I also observed this problem, but it also existed previously, with the ladndscape orientation. In my case it's not that big of an issue as I need it mostly in the direct position of the head towards camera. But I will also try to fix it- if I succeed I will certainly let you know. :)

**Comment by ArtSebus** [comment]
@teresakozera something off topic, could you please tell me how you got the landmarking lines working ? all I see in the app is the dots 

thanks

**Comment by stanchiang** [comment]
@ArtSebus probably just used the function dlib::draw_line(img, <#const point &p1#>, <#const point &p2#>, <#const pixel_type &val#>);

**Comment by ArtSebus** [comment]
@stanchiang could you please suggest what  should I  pass in for the parameters
`<#const point &p1#>, <#const point &p2#>, <#const pixel_type &val#>)`
 Sorry I am not that good with C programming

**Comment by stanchiang** [comment]
@ArtSebus haven't touched c in a few years myself haha. bit it looks like you's need to pass in a couple dlib::point that you want to connect and then specify what type of line you want to draw for the last one. I'd try inputing 3 for the value. No reason for that number, its just the same number that was used when drawing the dots in the existing code.

**Comment by stanchiang** [comment]
@teresakozera trying something a little different right now. i'm storing shape.parts[60-67] which make up the mouth in a separate array and trying to pass it into UIKit/SceneKit to draw it separately. 

`[m addObject: [NSValue valueWithCGPoint:CGPointMake( [DlibWrapper pixelToPoints:p.x()], [DlibWrapper pixelToPoints:p.y()]) ]];`

converting from pixels to points using this function https://gist.github.com/jordiboehmelopez/3168819

The problem it still seems stuck in the old bounds. sort of like the old screenshot i posted. I wasn't expecting this problem because we call `convertCGRectValueArray` before we loop through the shape.part array

**Comment by teresakozera** [comment]
@ArtSebus  line method, have a look at this: [https://github.com/chili-epfl/attention-tracker/blob/master/README.md](url) :)

@stanchiang - hmmm... a little bit odd. So with code from here and all the changes it works but when you try the above (a conversion from pixels to points) it detects landmarks in the other orientation? Does it happen after it is passed to UIKit or you check it before?

**Comment by stanchiang** [comment]
@teresakozera - yea it goes
[dlib] -1a-> [AVSampleBufferDisplayLayer display entire mask]
[dlib] -1b-> [DlibWrapperDelegate w/ array of only mouth vertices] -> [uikit/skscene (has same result)]

here's my code to show you what i mean 
https://github.com/stanchiang/face-landmarking-ios

if you go to gamescene.swift and comment out line 19: `if polygonNode != nil { polygonNode.removeFromParent() }`

it stops removing old node drawings and you can very see that it will only draw within the bounds of the old orientation with a very particular transformation. corners 1 and 3 are switched as indicated by the image below. 
![img_3624](https://cloud.githubusercontent.com/assets/3621407/17606369/0d8e1b50-5fd4-11e6-927e-4fe8a3c51c85.JPG)

**Comment by teresakozera** [comment]
@stanchiang- I will have a look at it on Monday, as today I'm heading for a little bit longer weekend. Anyway I hope you manage to solve this problem earlier. :) Have a nice weekend!

**Comment by morizotter** [comment]
@hoangdado @stanchiang Thanks! I used your solution and almost all problems solved. Later, I found the better - just I think - way.

I made pull request: https://github.com/zweigraf/face-landmarking-ios/pull/9 . In this pr, I convert faceObject in SessionHandler for fitting the given orientation.

How do you think??

**Comment by ArtSebus** [comment]
@teresakozera Could you suggest how to integrate [attentionTracker](https://github.com/chili-epfl/attention-tracker) into the project, I've tried for some time but still stuck and haven't got anywhere. almost close to pull my hairs out

**Comment by shaileshh** [comment]
@teresakozera  @hoangdado 
i am trying to convert this into objective c  using `AVCaptureStillImageOutput`,`AVCaptureVideoPreviewLayer`.
Im using` captureStillImageAsynchronouslyFromConnection: completionHandler: ^(CMSampleBufferRef imageSampleBuffer, NSError *error)` to capture still image and  convert CMSampleBufferRef to `uiimage` and display it on `Uiimageview`. but i get clicked image in landscape mode while im taking photo in portrait mode. same issue as  @stanchiang bt solution given by @stanchiang  doesn't work in objective c.
![issue](https://cloud.githubusercontent.com/assets/17401499/25699363/8d155fcc-30e0-11e7-88d2-cd80d066a189.png)

**Comment by Miths19** [comment]
i want to crop landmarked portion of the face...... i want only the face can any one help me for this

**Comment by trungnguyen1791** [comment]
@stanchiang You could easily change "VideoMirrored"  mode with this one instead of doing some manual transforms
`if (connection.isVideoMirroringSupported) {
            connection.isVideoMirrored = true;
        }`

**Comment by wangwenzhen** [comment]
@stanchiang I want to be able to support detection in both horizontal and vertical screens，can you provide sample demo ？

**Comment by liamwalsh** [comment]
*bump*
I'm still having this issue on the latest master - setting my AVCaptureConnection videoOrientation to portrait causes all of the feature points to be wrong.

**Comment by Hardy143** [comment]
@liamwalsh were you able to find a solution? I'm having the same problem as you.

**Comment by Hardy143** [comment]
@liamwalsh I found I was putting connection.videoOrientation = AVCaptureVideoOrientation.portrait in the wrong captureOutput function. It now works for me:

<img width="731" alt="screen shot 2018-07-05 at 17 45 26" src="https://user-images.githubusercontent.com/33378549/42336318-40bf43ea-807b-11e8-9573-6b9a9791d308.png">

**Comment by jpatel956** [comment]
@stanchiang 

First of thanks for your link.
https://github.com/stanchiang/face-landmarking-ios

I have succesfully run your code but not have one issue that you face earlier may be offset where my cgpoint coordinates have a weird offset for some reason.

Here I am getting error:

> validateTextureDimensions, line 759: error 'MTLTextureDescriptor has width (114046) greater than the maximum allowed size of 8192.'
> validateTextureDimensions:759: failed assertion `MTLTextureDescriptor has width (114046) greater than the maximum allowed size of 8192.'


can you please help me to come out.

Thanks

**Comment by ScientistMe** [comment]
Hi,
i'm dealing with this issue, and i'm not able to get it working in portrait mode. I've read all the threads here.
My guess is that in portrait mode i'm having a wrong proportions of the layer where the wrapper draws the points on it because the points looks distorted.
![IMG-4956](https://user-images.githubusercontent.com/44803516/87775581-a291d480-c826-11ea-8fb0-96ae7bb5edaf.jpg)
![IMG-4957](https://user-images.githubusercontent.com/44803516/87775588-a58cc500-c826-11ea-9f03-7022e6e82b89.jpg)


Can you please help me?

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @jaymine999, @tdhulster, @con17man, @elboletaire, @jcraywtf, @myself659, @subzerofx, @ekkans, @Pratyush-Ranjan, @wheng3, @zachyam, @ivaylomarinovski, @avmohan, @anthonylau, @sush987, @mehdijalaly, @francoishill, @humboldt-xie, @nathanp, @Cryptomikcoin, @gmorlima, @nickshater, @inbravo, @wasifhossain, @anhskrttt, @atimur, @AnthonyRChao, @Janithkjw, @rudenugget, @AlexanderCord, @armanijohnny, @riazrooshan, @Ag-E, @ianyh, @AndWa, @amnosuperman, @tanshul, @satyambnsal, @Jinxiansen, @hyperh, @f-a-a, @pantuflo, @elwarren, @Jono120, @PoliticalProgressor, @Masquerade0097, @bafbomb, @sixingxu, @PedroCastro, @Ploppz

**Comment by wonmor** [comment]
I managed to fix the issue of this solution not working on the latest version of the code base; just 4 years after.
What a long time it took me solve this.
Jokes aside, it actually took a decent time to figure this out:

If you go through the instructions provided in https://github.com/zweigraf/face-landmarking-ios/issues/5
You'll be able to quickly figure out that there's no convertScaleCGRect function in the recent version of this code base.

That's because the author has pushed a "simplified version" of DlibWrapper class, so I had to go through the previous commit history and I found it (the one in May 2016).

First and foremost, replace the entirety of your DlibWrapper.mm file to the following:
```
//
//  DlibWrapper.m
//  DisplayLiveSamples
//
//  Created by Luis Reisewitz on 16.05.16.
//  Copyright © 2016 ZweiGraf. All rights reserved.
//

#import "DlibWrapper.h"
#import <UIKit/UIKit.h>

#include <dlib/image_processing.h>
#include <dlib/image_io.h>

@interface DlibWrapper ()

@property (assign) BOOL prepared;

+ (dlib::rectangle)convertScaleCGRect:(CGRect)rect toDlibRectacleWithImageSize:(CGSize)size;
+ (std::vector<dlib::rectangle>)convertCGRectValueArray:(NSArray<NSValue *> *)rects toVectorWithImageSize:(CGSize)size;

@end
@implementation DlibWrapper {
    dlib::shape_predictor sp;
}


-(instancetype)init {
    self = [super init];
    if (self) {
        _prepared = NO;
    }
    return self;
}

- (void)prepare {
    NSString *modelFileName = [[NSBundle mainBundle] pathForResource:@"shape_predictor_68_face_landmarks" ofType:@"dat"];
    std::string modelFileNameCString = [modelFileName UTF8String];
    
    dlib::deserialize(modelFileNameCString) >> sp;
    
    // FIXME: test this stuff for memory leaks (cpp object destruction)
    self.prepared = YES;
}

-(void)doWorkOnSampleBuffer:(CMSampleBufferRef)sampleBuffer inRects:(NSArray<NSValue *> *)rects {
    
    if (!self.prepared) {
        [self prepare];
    }
    
    dlib::array2d<dlib::bgr_pixel> img;
    
    // MARK: magic
    CVImageBufferRef imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
    CVPixelBufferLockBaseAddress(imageBuffer, kCVPixelBufferLock_ReadOnly);

    size_t width = CVPixelBufferGetWidth(imageBuffer);
    size_t height = CVPixelBufferGetHeight(imageBuffer);
    char *baseBuffer = (char *)CVPixelBufferGetBaseAddress(imageBuffer);
    
    // set_size expects rows, cols format
    img.set_size(height, width);
    
    // copy samplebuffer image data into dlib image format
    img.reset();
    long position = 0;
    while (img.move_next()) {
        dlib::bgr_pixel& pixel = img.element();

        // assuming bgra format here
        long bufferLocation = position * 4; //(row * width + column) * 4;
        char b = baseBuffer[bufferLocation];
        char g = baseBuffer[bufferLocation + 1];
        char r = baseBuffer[bufferLocation + 2];
        //        we do not need this
        //        char a = baseBuffer[bufferLocation + 3];
        
        dlib::bgr_pixel newpixel(b, g, r);
        pixel = newpixel;
        
        position++;
    }
    
    // unlock buffer again until we need it again
    CVPixelBufferUnlockBaseAddress(imageBuffer, kCVPixelBufferLock_ReadOnly);

    CGSize imageSize = CGSizeMake(width, height);
    
    // convert the face bounds list to dlib format
    std::vector<dlib::rectangle> convertedRectangles = [DlibWrapper convertCGRectValueArray:rects toVectorWithImageSize:imageSize];
    
    // for every detected face
    for (unsigned long j = 0; j < convertedRectangles.size(); ++j)
    {
        dlib::rectangle oneFaceRect = convertedRectangles[j];
        
        // detect all landmarks
        dlib::full_object_detection shape = sp(img, oneFaceRect);
        
        // and draw them into the image (samplebuffer)
        for (unsigned long k = 0; k < shape.num_parts(); k++) {
            dlib::point p = shape.part(k);
            draw_solid_circle(img, p, 3, dlib::rgb_pixel(0, 255, 255));
        }
    }
    
    // lets put everything back where it belongs
    CVPixelBufferLockBaseAddress(imageBuffer, 0);

    // copy dlib image data back into samplebuffer
    img.reset();
    position = 0;
    while (img.move_next()) {
        dlib::bgr_pixel& pixel = img.element();
        
        // assuming bgra format here
        long bufferLocation = position * 4; //(row * width + column) * 4;
        baseBuffer[bufferLocation] = pixel.blue;
        baseBuffer[bufferLocation + 1] = pixel.green;
        baseBuffer[bufferLocation + 2] = pixel.red;
        //        we do not need this
        //        char a = baseBuffer[bufferLocation + 3];
        
        position++;
    }
    CVPixelBufferUnlockBaseAddress(imageBuffer, 0);
}

+ (dlib::rectangle)convertScaleCGRect:(CGRect)rect toDlibRectacleWithImageSize:(CGSize)size {
    long right = (1.0 - rect.origin.y ) * size.width;
    long left = right - rect.size.height * size.width;
    long top = rect.origin.x * size.height;
    long bottom = top + rect.size.width * size.height;
    
    dlib::rectangle dlibRect(left, top, right, bottom);
    return dlibRect;
}

+ (std::vector<dlib::rectangle>)convertCGRectValueArray:(NSArray<NSValue *> *)rects toVectorWithImageSize:(CGSize)size {
    std::vector<dlib::rectangle> myConvertedRects;
    for (NSValue *rectValue in rects) {
        CGRect singleRect = [rectValue CGRectValue];
        dlib::rectangle dlibRect = [DlibWrapper convertScaleCGRect:singleRect toDlibRectacleWithImageSize:size];
        myConvertedRects.push_back(dlibRect);
    }
    return myConvertedRects;
}

@end
```

I applied the changes made in the comments in issue #5 so that now it supports portrait mode.

Next change you need to make is...
Go to SessionHandler and locate the following:

```
 func captureOutput(_ output: AVCaptureOutput, didDrop sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        print("DidDropSampleBuffer")
    }
```

BE AWARE! There are TWO captureOutput(s) — you must choose the one which has NO code inside of the function block except for a simple print line. Then you wanna add the following inside the function: ``` connection.videoOrientation = AVCaptureVideoOrientation.portrait```

So the final version of SessionHandler's captureOutput function will look like the following:
```
func captureOutput(_ output: AVCaptureOutput, didDrop sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        print("DidDropSampleBuffer")
        connection.videoOrientation = AVCaptureVideoOrientation.portrait
    }
```

BOOM. All issues have been resolved. OH BY THE WAY, add ```session.sessionPreset = AVCaptureSession.Preset.vga640x480``` RIGHT BEFORE the ```  session.startRunning()``` line in ViewController.swift to enable legacy style video streaming (640x480 instead of 1024 something dimensions) so that there's LESS noise and instability in the landmark data. Lower resolution helps because it lowers the demand for the machine to handle.

Hope that helps, I know maybe I'm a little too late now that the Vision framework/ARKit framework is out, but in the case you're writing C++ code in tandem with Swift and want to import these stuff from C++ side too using Objective-C++ — this is a tutorial for you!

John Seong

**Comment by wonmor** [comment]
Never mind — you're supposed to add ```connection.videoOrientation = AVCaptureVideoOrientation.portrait``` to the OTHER captureOutput NOT the one I indicated above. Sorry.

**Comment by wonmor** [comment]
ANOTHER UPDATE - just replace the whole captureOutput to the following:
```
    // MARK: AVCaptureVideoDataOutputSampleBufferDelegate
    func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection) {
        connection.videoOrientation = AVCaptureVideoOrientation.portrait
        
        if !currentMetadata.isEmpty {
            let boundsArray = currentMetadata
                .compactMap { $0 as? AVMetadataFaceObject }
                .map { NSValue(cgRect: $0.bounds) }
            
            wrapper?.doWork(on: sampleBuffer, inRects: boundsArray)
        }
        
        layer.enqueue(sampleBuffer)
    }
```

You also have to tinker with changing the .map part to ```.map { NSValue(cgRect: $0.bounds) }```.
